#!/bin/zsh

# Bash support only one dimensional array so we put the name of the page first, and the URL to the page second
pages=(
	"Welcome to our Developer Portal"
	"https://developers.mindee.com/docs/what-is-mindee"
	"Setup your account"
	"https://developers.mindee.com/docs/setup-your-account"
	"Make your first request"
	"https://developers.mindee.com/docs/make-your-first-request"
	"Platform tour"
	"https://developers.mindee.com/docs/platform-tour"
	"Authentication"
	"https://developers.mindee.com/docs/authentication"
	"Endpoints"
	"https://developers.mindee.com/docs/endpoints"
	"Prediction"
	"https://developers.mindee.com/docs/prediction"
	"Annotation"
	"https://developers.mindee.com/docs/annotation"
	"Document inputs"
	"https://developers.mindee.com/docs/document-inputs"
	"Technical limitations"
	"https://developers.mindee.com/docs/limitations"
	"Error management"
	"https://developers.mindee.com/docs/error-management"
	"Receipt OCR"
	"https://developers.mindee.com/docs/receipt-ocr"
	"Invoice OCR"
	"https://developers.mindee.com/docs/invoice-ocr"
	"Passport OCR"
	"https://developers.mindee.com/docs/passport-ocr"
	"Build your document parsing API"
	"https://developers.mindee.com/docs/build-your-first-document-parsing-api"
	"Data model configuration"
	"https://developers.mindee.com/docs/data-model-configuration"
	"Text"
	"https://developers.mindee.com/docs/text"
	"Numbers"
	"https://developers.mindee.com/docs/numbers"
	"Dates"
	"https://developers.mindee.com/docs/dates"
	"Emails"
	"https://developers.mindee.com/docs/emails"
	"URLs"
	"https://developers.mindee.com/docs/urls"
	"Phone Number"
	"https://developers.mindee.com/docs/phones"
	"Document classification"
	"https://developers.mindee.com/docs/document-classification"
	"Training"
	"https://developers.mindee.com/docs/training-interface"
	"Train using the annotation endpoint"
	"https://developers.mindee.com/docs/train-using-the-annotation-endpoint"
	"Generate your clients"
	"https://developers.mindee.com/docs/generate-your-clients"
	"Test your API with Postman"
	"https://developers.mindee.com/docs/test-with-postman"
	"Predict Endpoint"
	"https://developers.mindee.com/docs/predict-endpoint"
	"Use-cases"
	"https://developers.mindee.com/docs/use-cases"
	"1040 Forms OCR"
	"https://developers.mindee.com/docs/1040-forms-ocr"
	"Affidavit of Residence OCR"
	"https://developers.mindee.com/docs/affidavit-of-residence-ocr"
	"Bank Checks OCR"
	"https://developers.mindee.com/docs/bank-checks-ocr"
	"Bank Statement OCR"
	"https://developers.mindee.com/docs/bank-statement-ocr"
	"Bill of Lading OCR"
	"https://developers.mindee.com/docs/bill-of-lading-ocr"
	"Birth Certificate OCR"
	"https://developers.mindee.com/docs/birth-certificate-ocr"
	"Blood Test Results OCR"
	"https://developers.mindee.com/docs/blood-test-results-ocr-1"
	"Boarding Pass OCR"
	"https://developers.mindee.com/docs/boarding-pass"
	"Bus Ticket OCR"
	"https://developers.mindee.com/docs/bus-ticket-ocr"
	"Certificate of Origin OCR"
	"https://developers.mindee.com/docs/certificate-of-origin-ocr"
	"Certificate of Status OCR"
	"https://developers.mindee.com/docs/certificate-of-status-ocr"
	"Commercial General Liability Section OCR"
	"https://developers.mindee.com/docs/commercial-general-liability-section-ocr"
	"Delivery Note OCR"
	"https://developers.mindee.com/docs/delivery-note-ocr"
	"Diploma OCR"
	"https://developers.mindee.com/docs/diploma-ocr"
	"DS 2019 OCR"
	"https://developers.mindee.com/docs/ds-2019-ocr"
	"Electricity Bill OCR"
	"https://developers.mindee.com/docs/electricity-bill-ocr"
	"Energy performance diagnostic OCR"
	"https://developers.mindee.com/docs/energy-performance-diagnostic-ocr"
	"French health insurance card OCR"
	"https://developers.mindee.com/docs/french-health-insurance-card-carte-mutuelle-ocr"
	"French Payslips OCR"
	"https://developers.mindee.com/docs/french-payslips"
	"Marriage Certificate OCR"
	"https://developers.mindee.com/docs/marriage-certificate-ocr"
	"Medical Certificate OCR"
	"https://developers.mindee.com/docs/blood-test-results-ocr"
	"Medical prescription OCR"
	"https://developers.mindee.com/docs/medical-prescription-ocr"
	"Medicare health insurance card OCR"
	"https://developers.mindee.com/docs/medicare-health-insurance-card-ocr"
	"Nutrition Facts label OCR"
	"https://developers.mindee.com/docs/nutrition-facts-label-ocr"
	"Packing List OCR"
	"https://developers.mindee.com/docs/packing-list-ocr"
	"Parking Ticket OCR"
	"https://developers.mindee.com/docs/parking-ticket-ocr"
	"Rent Receipt OCR"
	"https://developers.mindee.com/docs/rent-receipt-ocr"
	"Shipper's Letter of Instruction OCR"
	"https://developers.mindee.com/docs/shippers-letter-of-instruction-ocr"
	"SS4 OCR"
	"https://developers.mindee.com/docs/ss4-ocr"
	"Traffic Ticket OCR"
	"https://developers.mindee.com/docs/traffic-ticket-ocr"
	"Train Ticket OCR"
	"https://developers.mindee.com/docs/train-ticket-ocr"
	"US Employment Authorization OCR"
	"https://developers.mindee.com/docs/us-employment-authorization-ocr"
	"US Pay Stubs OCR"
	"https://developers.mindee.com/docs/us-pay-stubs"
	"US Visa OCR"
	"https://developers.mindee.com/docs/us-visa-ocr"
	"W9 forms OCR"
	"https://developers.mindee.com/docs/w9-forms-ocr"
	"Python SDK"
	"https://developers.mindee.com/docs/python-sdk"
	"Getting started"
	"https://developers.mindee.com/docs/getting-started"
	"Python Receipt OCR"
	"https://developers.mindee.com/docs/python-receipt-ocr"
	"Python Invoice OCR"
	"https://developers.mindee.com/docs/python-invoice-ocr"
	"Python Passport OCR"
	"https://developers.mindee.com/docs/python-passport-ocr"
	"Node.js SDK"
	"https://developers.mindee.com/docs/nodejs-sdk"
	"Getting started"
	"https://developers.mindee.com/docs/getting-started-1"
	"Node.js invoice OCR"
	"https://developers.mindee.com/docs/nodejs-invoice-ocr"
	"Node.js receipt OCR"
	"https://developers.mindee.com/docs/nodejs-receipt-ocr"
	"No code: Zapier"
	"https://developers.mindee.com/docs/no-code"
)

totalpages=${#pages[@]}

# use for loop to read all values and indexes
for (( i=1; i<${totalpages}; i=i+1 ));
do
	title=${pages[$i]}
	i=i+1
	url=${pages[$i]}

	curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token '${GITHUB_STARS_TOKEN}'" https://api.github.com/repos/mindee/documentation/issues -d '{"title":"Review the \"'${title}'\" documentation page", "body":"Review the ['${title}']('${url}') documentation page", "owner":"fharper", "assignees":["fakela"]}'

	# Do not change as you can be banned caused of the limitation of call on GH
	sleep 10
done
