name: Markdown Check
on: push

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing markdownlint-cli2
        run: npm i -g markdownlint-cli2

      - name: Check the Markdown
        run: markdownlint-cli2-config .markdownlint.json "**/*.md"
