name: Spelling Validation
on: push

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rojopolis/spellcheck-github-actions@0.30.0
      name: Spellcheck
      with:
        config_path: .pyspelling.yml
